image: gitpod/workspace-full-vnc


tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y \
          python3-pip \
          zlib1g-dev \
          libncurses5-dev \
          libgdbm-dev \
          libnss3-dev \
          libssl-dev \
          libsqlite3-dev \
          libreadline-dev \
          libffi-dev \
          autoconf \
          automake \
          libtool \
          openjdk-17-jdk
      pip3 install --upgrade buildozer cython
      
      # Установка Android SDK
      mkdir -p /home/gitpod/.android
      touch /home/gitpod/.android/repositories.cfg
      yes | sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
      yes | sdkmanager "ndk;23.2.8568313"

  - command: chmod +x /home/gitpod/.buildozer/android/platform/android-sdk/tools/bin/*
  - command: buildozer -v android debug
